cache:
  paths:
    - env.txt

foo:
  stage: .pre
  tags:
    - bb5
  script:
    - echo ${PWD}
    - env > env.txt
    - ls
  after_script:
    - ls

bar:
  stage: build
  tags:
    - bb5
  before_script:
    - ls $HOME
  script:
    - ls

touchdetector:
  stage: test
  variables:
    CI_PROJECT_PARENT_REF: ${CI_COMMIT_SHA}
  trigger:
    project: hpc/touchdetector
    branch: ci
