cache:
  key: foo
  paths:
    - env.txt

foo:
  stage: .pre
  tags:
    - bb5
  script:
    - echo ${PWD}
    - env > env.txt
    - ls -R ../../..
    - ls -a $HOME

bar:
  stage: build
  tags:
    - bb5
  script:
    - ls -R ../../..
    - ls -a $HOME

touchdetector:
  stage: test
  variables:
    CI_PROJECT_PARENT_REF: ${CI_COMMIT_SHA}
  trigger:
    project: hpc/touchdetector
    branch: ci
