rules:
  - if: '$CI_PIPELINE_SOURCE != "parent_pipeline"'
    when: never

spam:
  stage: .pre
  tags:
    - bb5
  script:
    - echo "I'm just a piece of shit job to trigger things!"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "parent_pipeline"'
      when: always
  parallel:
    matrix:
      - MY_SECRETION: [barf, blarf]
  trigger:
    include:
      - local: .gitlab-ci.yml
        variables:
          MY_SECRET: ${MY_SECRETION}

ham:
  stage: build
  tags:
    - bb5
  script:
    - echo ${MY_SECRET}
