foo:
  stage: build
  tags:
    - bb5
  script:
    - echo ${PWD}

touchdetector:
  stage: test
  variables:
    CI_PROJECT_PARENT_REF: ${CI_COMMIT_SHA}
  trigger:
    project: hpc/touchdetector
    branch: ci
