test_functionalizer:
  stage: test
  trigger:
    project: hpc/circuit-building/spykfunc
    strategy: depend
  variables:
    GITLAB_PIPELINES_BRANCH: ${CI_COMMIT_BRANCH}
test_touchdetector:
  stage: test
  trigger:
    project: hpc/circuit-building/touchdetector
    strategy: depend
  variables:
    GITLAB_PIPELINES_BRANCH: ${CI_COMMIT_BRANCH}
test_coreneuron:
  stage: test
  trigger:
    project: hpc/coreneuron
    strategy: depend
  variables:
    GITLAB_PIPELINES_BRANCH: ${CI_COMMIT_BRANCH}
