build:
  tags:
    - bb5
  stage: build
  script:
    - mkdir -p foo
    - touch foo/{spam,ham,eggs}
  artifacts:
    paths:
      - foo/

test 1: &foo
  needs:
    - build
  stage: test
  tags:
    - bb5
  script:
    - pwd
    - ls -l foo

test 2: *foo
test 3: *foo
test 4: *foo
test 5: *foo
test 6: *foo
