build:
  tags:
    - bb5
  stage: build
  script:
    - mkdir -p foo
    - touch foo/{spam,ham,eggs}
  artifacts:
    paths:
      - foo/

test 1:
  needs:
    - build
  stage: test
  tags:
    - bb5
  script:
    - ls

test 2:
  needs:
    - build
  stage: test
  tags:
    - bb5
  script:
    - ls

test 3:
  needs:
    - build
  stage: test
  tags:
    - bb5
  script:
    - ls
