spam:
  stage: .pre
  tags:
    - bb5
  script:
    - module load unstable python
    - python generate.py > putin.yml
  artifacts:
    paths:
      - putin.yml

triggered:
  stage: build
  trigger: putin.yml
