# The -components version includes the actual implementation, but it is all
# packaged up as hidden targets (beginning with .) so no jobs are created by
# default. This is useful if you want to assemble a more complicated pipeline.
# This file simply imports the components and declares real jobs using them,
# which saves boilerplate if a simple pipeline is sufficient.
include:
  - local: spack-build-components.gitlab-ci.yml

# Set up Spack
spack_setup:
  extends: .spack_setup

spack_build:
  extends: .spack_build
