include:
  - local: spack-build.gitlab-ci.yml

.spack_test:
  stage: test
  resource_group: test
  tags:
    - bb5
  cache:
    <<: *default_cache
    policy: pull
  before_script:
    - unset $(env|awk -F= '/^(PMI|SLURM)_/ {if (match($1, "_(ACCOUNT|PARTITION)$")==0) print $1}')
    - . spack/share/spack/setup-env.sh
    - spack env activate blargh
  script:
    - echo MOOO

ctest:
  extends: .spack_test
  script:
    - cd $(find . -type d -name "spack-build-*")
    - i_am_a_failure=0
    - spack build-env ${SPACK_PACKAGE}@develop ctest -T Test || i_am_a_failure=1
    - module load unstable spykfunc
    - python ~matwolf/xunit2junit.py > ../ctest.xml
    - exit ${i_am_a_failure}
  artifacts:
    when: always
    paths:
      - ctest.xml
    reports:
      junit:
        - ctest.xml
