include:
  - local: spack-build.gitlab-ci.yml

default:
  stage: test

ctest:
  script:
    - unset $(env|awk -F= '/^(PMI|SLURM)_/ {if (match($1, "_(ACCOUNT|PARTITION)$")==0) print $1}')
    - . spack/share/spack/setup-env.sh
    - spack env activate blargh
    - cd $(find . -type d -name "spack-build-*")
    - i_am_a_failure=0
    - spack build-env ${SPACK_PACKAGE}@develop ctest -T Test || i_am_a_failure=1
    - module load unstable spykfunc
    - python ~matwolf/xunit2junit.py > ../ctest.xml
    - exit ${i_am_a_failure}
  artifacts:
    when: always
    paths:
      - ctest.xml
    reports:
      junit:
        - ctest.xml
