variables:
  GIT_SUBMODULE_STRATEGY: recursive

  DATADIR: /gpfs/bbp.cscs.ch/project/proj12/jenkins/

  SALLOC_ACCOUNT: proj12
  SBATCH_ACCOUNT: proj12
  SLURM_ACCOUNT: proj12

  SALLOC_PARTITION: prod
  SBATCH_PARTITION: prod
  SLURM_PARTITION: prod

spack_setup:
  stage: .pre
  tags:
    - bb5
  script:
    - git clone --depth 1 --single-branch https://github.com/BlueBrain/spack.git
    - cp /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/config/*.yaml spack/etc/spack
    - . spack/share/spack/setup-env.sh
    - spack env create blargh
    - spack env activate blargh
    - spack add ${SPACK_PACKAGE}@develop${SPACK_SPEC}
    - spack develop -p ${PWD} --no-clone ${SPACK_PACKAGE}@develop${SPACK_SPEC}
  artifacts:
    paths:
      - spack/

spack_build:
  stage: build
  tags:
    - bb5
  dependencies:
    - spack_setup
  script:
    - unset $(env|awk -F= '/^(PMI|SLURM)_/ {if (match($1, "_(ACCOUNT|PARTITION)$")==0) print $1}')
    - . spack/share/spack/setup-env.sh
    - spack env activate blargh
    # Git is needed, otherwise the shitty RH version fails
    - module load unstable git
    - spack install --log-format=junit --log-file=install.xml
  artifacts:
    when: always
    paths:
      - install.xml
      - spack/
      - spack-build-*/
    reports:
      junit:
        - install.xml
